uploads = []
generated = []

[[outputs]]
id = "LRk8lJSPLB4G6dDV56B-k"
uri = "file://personal-key-wallet.zip"
type = "unspecified"
title = "Personal Key Wallet — Full Project Source"

[[outputs]]
id = "EBAGQD2c-xASFWeUd_91P"
uri = "file://personal-key-wallet-final.zip"
type = "unspecified"
title = "Personal Key Wallet — Final Source (with all new features)"

[[outputs]]
id = "pwvDQz8BGRO9xop4NSDYz"
uri = "file://personal-key-wallet-v2.zip"
type = "unspecified"
title = "Personal Key Wallet v2 — All Improvements"
